machine:
  services:
    - docker

dependencies:
  pre:
    - docker info && docker version
    
  override:
    - docker pull million12/nginx:latest

# Run tests
test:
  pre:
    - docker build -t million12/nginx-php .

  override:
    # Launch it
    - docker run -d -p 8080:80 --name nginx million12/nginx-php
    - while true; do if docker logs nginx | grep "nginx entered RUNNING state"; then break; else sleep 1; fi done
    # Add phpinfo
    - docker run -ti --volumes-from nginx million12/nginx-php "echo '<?php phpinfo();' >> /data/www/default/index.php"
    # Check phpinfo page
    - curl -s --show-error http://localhost:8080 | grep 'PHP Version 5.6'
    
    # Check if we have PECL extensions installed / loaded
    - curl -s --show-error http://localhost:8080 | grep 'LibYAML Support'
    - curl -s --show-error http://localhost:8080 | grep 'Redis Version'
    
    # Check if we have common dev tools working
    - docker run -ti million12/nginx-php "ruby -v"
    - docker run -ti million12/nginx-php "gem -v"
    - docker run -ti million12/nginx-php "node -v"
    - docker run -ti million12/nginx-php "npm -v"
    - docker run -ti million12/nginx-php "grunt --version"
    - docker run -ti million12/nginx-php "gulp -v"
